BaseURL = "https://buhuipao.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "不会跑"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"
paginate = 10
paginatePath = "post"

[Author]
  Name = "buhuipao"

[Params]
  AuthorHomepage = "https://www.buhuipao.com"
  BottomIntroduce = "《深入理解计算机系统》<br>《UNIX环境高级编程》"
  Description = ""
  Subtitle = "不忘初心，方得始终"
  Weibo = "buhuipao"
  WeiboID = 5250083917
  Twitter = "buhuipao"
  GitHub = "buhuipao"
  Facebook = "profile.php?id=100009431134667"
  LinkIn = "in/华-陈-26a19313a"
  Imglogo = "img/buhuipao-logo.svg"
  AuthorImg = "img/buhuipao.png"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  # DuoShuoShortName = "coderzh"
  DisqusShortName = "buhuipao"
  GoogleAnalyticsID = "UA-109197138-1"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "学习总结"
    URL = "/note"
    Weight = 2
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 3
