title = "不会跑"
baseURL = "https://buhuipao.com/"
languageCode = "zh-CN"
hasCJKLanguage = true
theme = "hugo-ink"
pygmentsStyle = "default"
pygmentsUseClasses = true

paginate = 10
paginatePath = "post"

copyright = "© Copyright buhuipao"

googleAnalyticsID = "UA-109197138-1"
disqusShortname = "buhuipao"


[author]
  name = "buhuipao"

[params]
  subtitle = "work for life"
  avatar = "https://avatars.githubusercontent.com/u/14309948?v=4"
  featherIconsCDN = false
  mode = "auto"
  favicon = "https://avatars.githubusercontent.com/u/14309948?v=4"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1
[[menu.main]]
  name = "文章"
  url = "/post"
  weight = 2
[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 3
[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/buhuipao"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
  tag = "tags"
