title = "不会跑"
baseURL = "https://buhuipao.com/"
languageCode = "zh-CN"
hasCJKLanguage = true
theme = "hugo-ink"
pygmentsStyle = "default"
pygmentsUseClasses = true

paginate = 10
paginatePath = "post"

copyright = "© Copyright buhuipao | <a href='https://beian.miit.gov.cn/' target='_blank'>粤ICP备2023051785号-1</a> <script> var _hmt = _hmt || []; (function() { var hm = document.createElement('script'); hm.src = 'https://hm.baidu.com/hm.js?f06b1a2b4a0b17b377b0bfac3f0d1a33'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(hm, s); })(); </script>"

googleAnalyticsID = "UA-109197138-1"
disqusShortname = "buhuipao"


[author]
  name = "buhuipao"

[params]
  subtitle = "work for life"
  avatar = "https://avatars.githubusercontent.com/u/14309948?v=4"
  featherIconsCDN = false
  mode = "auto"
  favicon = "https://avatars.githubusercontent.com/u/14309948?v=4"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1
[[menu.main]]
  name = "文章"
  url = "/post"
  weight = 2
[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 3
[[menu.main]]
  name = "标签"
  url = "/tags"
  weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/buhuipao"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
  tag = "tags"
